### ISSUE TITLE
About running AutoFolio with option '--tune'

### ISSUE THREAD

**Issue by chuanluocs** [mlindauer/AutoFolio#4]
Hi, I want use AutoFolio to train a algorithm selector from a collection of algorithms. However, I encounter an issue with using option '-t'. For example, I have two csv files for storing feature data (each instance has 54 features, i.e., the size of each instance's feature vector is 54) and performance data (using runtime as performance metric), respectively.

I first run the command to construct the portfolio selector:
`python3.5 <AutoFolio_Path>/AutoFolio-master/scripts/autofolio --performance_csv <Performance_Data_Path>/performance_data.csv --feature_csv <Feature_Data_Path>/
[csv_files.zip](https://github.com/mlindauer/AutoFolio/files/1205204/csv_files.zip)
feature_data.csv --objective runtime --runtime_cutoff 10 --tune --save autofolio_test`

Then I run the command to run the portfolio selector:
`python3.5 Components/AutoFolio-master/scripts/autofolio --load autofolio_test --feature_vec [54 float numbers separated by space (character ' ')]`

The terminal outputs:

> /usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 4294, in create_block_manager_from_blocks
    placement=slice(0, len(axes[0])))]
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 2719, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 115, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 54, placement implies 3

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "Components/AutoFolio-master/scripts/autofolio", line 19, in <module>
    af.run_cli()
  File "/home/lightning/luo/projects/Sparkle/Sparkle_source_codes/Components/AutoFolio-master/autofolio/autofolio.py", line 89, in run_cli
    model_fn=args_.load, feature_vec=list(map(float, args_.feature_vec)))
  File "/home/lightning/luo/projects/Sparkle/Sparkle_source_codes/Components/AutoFolio-master/autofolio/autofolio.py", line 293, in read_model_and_predict
    feature_vec, index=["pseudo_instance"], columns=scenario.feature_names)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 306, in __init__
    copy=copy)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 483, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 4303, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 4280, in construction_error
    passed, implied))
ValueError: Shape of passed values is (54, 1), indices imply (3, 1)

It seems that AutoFolio recognizes the number of feature size is 3, and the program terminates. However, if I do not use the option '--tune', the program will outputs a schedule list with algorithm and budget.

Could you help me to solve this issue?
Please find my csv files in the attachment.

Thanks very much for your help in advance!

[csv_files.zip](https://github.com/mlindauer/AutoFolio/files/1205205/csv_files.zip)

**Comment by mlindauer** [comment]
Hi,

There was a bug if a PCA was used (which was enabled because of the option "--tune" ).
I fixed the bug in the master branch.

Cheers,
Marius
